apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: cicd-project7-deployment
spec:
  selector:
    matchLabels:
      app: cicd-project7
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: cicd-project7
    spec:
      containers:
        - name: cicd-project7
          image: madeep2669/cicd-project7:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1
kind: Service
metadata:
  name: cicd-project7-ssvc
  namespace: webapps
spec:
  selector:
    app: cicd-project7
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Ensure this line exists without any type specification

  
